### ISSUE TITLE
Consonants question

### ISSUE THREAD

**Issue by davelab6** [motaitalic/vesper-libre#10]
In http://www.impallari.com/testing/index-devanagari.php here is the rendering of 

> ऱ्क ऱ्ख ऱ्ग ऱ्घ ऱ्ङ ऱ्च ऱ्छ ऱ्ज ऱ्झ ऱ्ञ ऱ्ट ऱ्ठ ऱ्ड ऱ्ढ ऱ्ण ऱ्त ऱ्थ ऱ्द ऱ्ध ऱ्न ऱ्ऩ ऱ्प ऱ्फ ऱ्ब ऱ्भ ऱ्म ऱ्य ऱ्र ऱ्ऱ ऱ्ल ऱ्ळ ऱ्ऴ ऱ्व ऱ्श ऱ्ष ऱ्स ऱ्ह ऱ्क़ ऱ्ख़ ऱ्ग़ ऱ्ज़ ऱ्ड़ ऱ्ढ़ ऱ्फ़ ऱ्य़ 

with the current version from this repo:

![screen shot 2015-05-11 at 12 43 29 am](https://cloud.githubusercontent.com/assets/261579/7556766/d54a9fe6-f776-11e4-83c4-b81ecce664af.png)

Here is the Devanagari MT mac default:

![screen shot 2015-05-11 at 12 43 24 am](https://cloud.githubusercontent.com/assets/261579/7556767/d55f37e4-f776-11e4-8ab0-86fe59f320e5.png)

These look very different... why do they look so different? :)

**Comment by motaitalic** [comment]
Vesper's is correct, there is a bug with the Devanagari MT version – it's rendering with the wrong half form.

**Comment by davelab6** [comment]
Thanks for explaining :)
