### ISSUE TITLE
Some Nukta positions

### ISSUE THREAD

**Issue by davelab6** [motaitalic/vesper-libre#11]
With the current version, the nukta position of these glyphs looks like it can be improved :)

> ऴ्फ़ ऴ्य़ ऴ्ज़ ऴ्क़ ऴ्ख़ 

Image from http://www.impallari.com/testing/index-devanagari.php :

![screen shot 2015-05-11 at 12 48 20 am](https://cloud.githubusercontent.com/assets/261579/7556780/73ab6a9e-f777-11e4-9e29-62d7ff5ffdd0.png)

**Comment by motaitalic** [comment]
Thanks for catching this; the half form had a misplaced anchor. I've corrected the position and added some spacing for when nukes follow it as well. Will push an update later today!

**Comment by davelab6** [comment]
Any luck with this? :)

**Comment by motaitalic** [comment]
Sorry... two days ago I hit commit, but didn't sync! It's online now!
