### ISSUE TITLE
Minor changes

### ISSUE THREAD

**Issue by davelab6** [motaitalic/vesper-libre#12]
- [x] NAME table IDs with `platformID=1` should be removed
- [x] ttfautohint settings should be recorded in the NAME table ID 5
- [x] `Heavy` style should be renamed to `Black`
- [x] Heavy style should not be style linked as Medium Bold, only Regular-Bold and Italic-BoldItalic should be style linked

**Comment by motaitalic** [comment]
Hi Dave,
I'm on these changes. As I understood it, Google converts and re-generates all the fonts anyway, so why are the extra name tables not automatically deleted on your end?

Also, why do you suggest renaming Heavy to Black? Sounds like a very arbitrary request without any reason. In this case the weight naming seems more like a design decision than a technical requirement.

**Comment by davelab6** [comment]
> [you] converts and re-generates all the fonts anyway

Hmm, we got our wires crossed somewhere; I take your TTFs directly

> so why are the extra name tables not automatically deleted on your end?

They can be, but its good to keep your sources in sync with the primary distribution

> why do you suggest renaming Heavy to Black? Sounds like a very arbitrary request without any reason. In this case the weight naming seems more like a design decision than a technical requirement.

Its important to me to use the same naming scheme in all the families :)

**Comment by motaitalic** [comment]
Done!
