### ISSUE TITLE
Improve release versioning

### ISSUE THREAD

**Issue by davelab6** [motaitalic/vesper-libre#5]
Github has a release versioning system - https://www.google.com/search?q=github+releases - which would be good to use. 

I also recommend adopting the www.semver.org version numbering convention.

**Comment by motaitalic** [comment]
Thanks for the info! Font naming is a bit different, with just the X.XXX numbers only option. But do you suggest we update the fonts now with a new major version (maybe 2.0), indicating the new release?

**Comment by davelab6** [comment]
Sorry I missed this! I think a 2.0 would make sense only if the metrics drastically change; otherwise incrementing the minor version number, even for patches, makes sense :)

**Comment by motaitalic** [comment]
Ok! Thanks!
