### ISSUE TITLE
Improve comparison page in Testing PDF

### ISSUE THREAD

**Issue by davelab6** [motaitalic/vesper-libre#6]
https://github.com/motaitalic/vesper-libre/blob/master/Samples/VesperLibreTest.pdf is awesome, but the line breaking of the comparison page 5 with Adobe Devanagari is different in either sample, so its inconvenient to locate the corresponding glyphs. Perhaps the line breaking could be the same, or instead of 
```
aaaaa
bbbbb
ccccc

xxxxx
yyyyy
zzzzz
```
you could interleave them like

```
aaaaa
xxxxx
bbbbb
yyyyy
ccccc
zzzzz
```

**Comment by motaitalic** [comment]
Sorry Dave but I don't follow you. This isn't a comparison test with Adobe Devanagari... It's meant to simply show Vesper's weights next to each other. But even when I change the fonts to Adobe Devanagari I'm getting the same line breaks... So I'm really not sure about the issue you are asking about.

**Comment by davelab6** [comment]
I got confused :) Never mind :)
