### ISSUE TITLE
Inconsistent copyright strings 

### ISSUE THREAD

**Issue by davelab6** [motaitalic/vesper-libre#9]
The copyright strings should match in 

- [x] the LICENSE file
- [x] the source `.glyphs` file
- [x] the binaries' `NAME` tables

The string should be `Copyright (c) 2007, Rob Keller (info@motaitalic.com)`

**Comment by motaitalic** [comment]
Hi Dave,

We discussed this months back and we agreed that it is not necessary to add the email address to the copyright string.

I have changed the year and made all strings: Copyright (c) 2007, Rob Keller (www.motaitalic.com)

And regarding my last question, what is your preferred solution?

>> The vertical metrics may cause clipping because they are not the ymin/ymax of the font:
>> 
> One technical question: Should the metrics match across all the weights (meaning should I make the heavy min/max for all weights), or is it better to set each weight individually? 

Cheers,
Rob

**Comment by davelab6** [comment]
Ahh yes, www is fine :)

Yes, all vertical metrics in the family should be even, otherwise line
spacing can be irregular inside a paragraph, when you use a style on one
line it can be different to the others
